spring:
  application:
    name: eureka-client
server:
  port: ${PORT:0} #Esto hace que spring elija un puerto aleatorio. Util en el caso de levantar varios pods

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
